language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "marouaneelkamel-github"
    token:
      secure: "13eaf841f8898bc9f3e89aac80e824dc98bb56d6"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)